server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.230.129:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false

  rabbitmq:
    host: 192.168.230.129
    port: 5672
    virtual-host: /lijin
    username: lijin
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 3
feign:
  sentinel:
    enabled: true

#  spring.rabbitmq.host=192.168.230.129
#  spring.rabbitmq.port=5672
#  spring.rabbitmq.virtual-host=/lijin
#  spring.rabbitmq.username=lijin
#  spring.rabbitmq.password=123456
#  spring.rabbitmq.listener.simple.prefetch=1
#  # 开启多线程消费，设置管道数为3个
#  spring.rabbitmq.listener.simple.concurrency=3
#
#  spring.rabbitmq.listener.simple.acknowledge-mode=manual