#server:
#  port: 8888
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 8791
#        dashboard: localhost:8080
#    gateway:
#      routes:
#        - id: pms-route
#          uri: lb://pms-service
#          predicates:
#            - Path=/pms/**
#        - id: oms-route
#          uri: lb://oms-service
#          predicates:
#            - Path=/oms/**
#        - id: sms-route
#          uri: lb://sms-service
#          predicates:
#            - Path=/sms/**
#        - id: ums-route
#          uri: lb://ums-service
#          predicates:
#            - Path=/ums/**
#        - id: wms-route
#          uri: lb://wms-service
#          predicates:
#            - Path=/wms/**
#        - id: search-route
#          uri: lb://search-service
#          predicates:
#            - Path=/search/**
#        - id: index-route
#          uri: lb://index-service
#          predicates:
#            - Host=gmall.com,index.gmall.com,www.gmall.com
#          filters:
#            - AddResponseHeader=xxx,yyy,zzz
#            - Auth=/
#        - id: index-route
#          uri: lb://index-service
#          predicates:
#            - Path=/index/**
#        - id: item-route
#          uri: lb://item-service
#          predicates:
#            - Host=item.gmall.com
#        - id: auth-route
#          uri: lb://auth-service
#          predicates:
#            - Host=sso.gmall.com
#auth:
#  jwt:
#    publicPath: F:\Java\gmall-0522\project-0522\rsa\rsa.pub
#    cookieName: GMALL-TOKEN


server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Host=gmall.com, index.gmall.com, www.gmall.com
          filters:
            - AddResponseHeader=xxx,yyy,zzz
            - Auth=/
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
auth:
  jwt:
    pubKeyPath: F:\Java\gmall-0522\project-0522\rsa\rsa.pub
    cookieName: GMALL-TOKEN
