server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8791
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms
    username: root
    password: 123456
  redis:
    host: 192.168.230.129
  rabbitmq:
    host: 192.168.230.129
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: /lijin
    username: lijin
    password: 123456

feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/pms/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto
