server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8791
        dashboard: localhost:8080

  zipkin:
    base-url: localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli_ums
  redis:
    host: 192.168.230.129
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/ums/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto